name: first workflow

on:
  push:
    branches:
      -master
    pull_request:
    branches:
      -main
    workflow_dispatch:
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      -name: hello world
        run: echo "Hello World"
        shell: bash
  

