name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PW }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: docker.io/username/my-repo:latest

    - name: Deploy to Production Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DO_IP }}
        username: ${{ secrets.DO_USER }}
        key: ${{ secrets.DO_SSH }}
        script: |
          docker pull docker.io/ck5150/newtest:latest
          docker pull docker.io/ck5150/oldtest:latest
          docker-compose down || true
          docker-compose up -d
