# .air.toml
root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -buildvcs=false -o ./tmp/main ./cmd"
bin = "./tmp/main"
exclude_dir = ["assets", "tmp", "vendor", "tests"]
include_ext = ["go", "tpl", "tmpl", "html"]
delay = 1000

[log]
time = true

[misc]
clean_on_exit = true
